on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        user: [sondrelg]
        package: [base, does-not-exist]

    steps:
      - name: Check for package
        run: curl --silent --head --write-out "%{http_code}" -u token:${{ secrets.READ_PACKAGES_TOKEN }} https://api.github.com/users/${{ matrix.user }}/packages/docker/${{ matrix.package }}

      - uses: actions/github-script@v3
        id: check-for-tag
        with:
          github-token: ${{ secrets.READ_PACKAGES_TOKEN }}
          result-encoding: json
          script: |
            try {
              const response = await github.request("GET /users/${{ env.OWNER }}/packages/docker/${{ env.PACKAGE_NAME }}/versions",
                { per_page: 100
              });
              for(version of response.data) {
                const tags = version.metadata.docker.tags
                for (var i = 0; i < tags.length; i++) {
                  if (tags[i] === "${{ env.TAG }}") {
                    return true
                  }
                }
              }
            } catch(err) {
              console.log(`status: ${err.status}`)
            }
            return false
        env:
          OWNER: ${{ matrix.user }}
          PACKAGE_NAME: ${{ matrix.package }}
          TAG: latest

      - name: Show result
        run: echo "${{ steps.check-for-tag.outputs.result }}"

      - name: Run if tags doesn't exist
        if: ${{ steps.check-for-tag.outputs.result == 'false' }}
        run: echo "Tag does not exist!"
