on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        user: [sondrelgckages]
        package: [base, does-not-exist]

    steps:
      - name: Check for package
        run: curl --silent --head --write-out "%{http_code}" -u token:${{ github.token }} https://api.github.com/users/${{ matrix.user }}/packages/docker/${{ matrix.package }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            const response = await github.request("GET /users/${{ env.OWNER }}/packages/docker/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                console.log("version.name: " + version.name)
            }
        env:
          OWNER: ${{ matrix.user }}
          PACKAGE_NAME: ${{ matrix.package }}
          PER_PAGE: 100
